# Generated by Django 4.1.5 on 2023-01-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoISBN', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=25)),
                ('titulo', models.CharField(max_length=25)),
                ('editorial', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
